# version: '3.8'

services:
  nginx:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: challenge3-nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service

  node-service:
    build: 
      context: ./docker/api
      dockerfile: Dockerfile
    image: challenge3-node-service
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    build: 
      context: ./docker/db
      dockerfile: Dockerfile
    image: challenge3-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      # - db-data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

# volumes:
#   db-data: